"""Add fixed income investments table

Revision ID: 4c5be83baaed
Revises: 06689bde056a
Create Date: 2026-01-12 13:06:22.844572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5be83baaed'
down_revision: Union[str, None] = '06689bde056a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_income_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TESOURO_SELIC', 'TESOURO_PREFIXADO', 'TESOURO_PREFIXADO_JUROS', 'TESOURO_IPCA', 'TESOURO_IPCA_JUROS', 'CDB', 'LCI', 'LCA', 'LC', 'DEBENTURE', 'CRI', 'CRA', 'POUPANCA', 'OUTRO', name='fixedincometype'), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('invested_amount', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('indexer', sa.Enum('SELIC', 'CDI', 'IPCA', 'IGPM', 'PREFIXADO', 'TR', 'OUTRO', name='indexertype'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_percentage_of_indexer', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('gross_value', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_income_investments_id'), 'fixed_income_investments', ['id'], unique=False)
    op.create_index(op.f('ix_fixed_income_investments_user_id'), 'fixed_income_investments', ['user_id'], unique=False)
    # Note: SQLite does not support ALTER COLUMN, skipping nullable change for transactions.created_at
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fixed_income_investments_user_id'), table_name='fixed_income_investments')
    op.drop_index(op.f('ix_fixed_income_investments_id'), table_name='fixed_income_investments')
    op.drop_table('fixed_income_investments')
    # ### end Alembic commands ###

